### ISSUE TITLE
Code errors

### ISSUE THREAD

**Issue by cara-tm** [michaelkpate/mkp_if_amp#1]
This part need to be corrected:

// TXP 4.6 tag registration
if (class_exists('Textpattern_Tag_Registry')) {
    Txp::get('Textpattern_Tag_Registry')
        ->register('mkp_if_amp')
    ;
}

Change it with:

// TXP 4.6 tag registration
if (class_exists('\Textpattern\Tag\Registry')) {
    Txp::get('\Textpattern\Tag\Registry')
        ->register('mkp_if_amp')
    ;
}

**Comment by michaelkpate** [comment]
Thank you. I have corrected the code.

**Comment by cara-tm** [comment]
;)
